version: '3.8'
services: 
  # jwtapi:
  #   image: jwtwebapitest
  #   ports:
  #     - 6600:6600
  #   depends_on:
  #     - db
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - DB_CONNECTION_STRING:="host=db;Database=JwtWebApi;Port=5432;User ID=postgres;Password=123;"
  db:
    image: postgres:14.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: codingTest

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ~/minio/data:/data \
    environment:
      MINIO_ROOT_USER : "MINIO"
      MINIO_ROOT_PASSWORD: "12345678"
      MINIO_STORAGE_USE_HTTPS: False
    command: server /minio/storage --console-address :9001
    
